create table if not exists public.portfolio_projects (
  id text primary key,
  project_index text not null,
  title text not null,
  project_type text not null,
  category text not null,
  href text not null,
  external boolean not null default true,
  summary text not null,
  pattern text not null,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.portfolio_skills (
  id bigint generated by default as identity primary key,
  group_key text not null,
  group_label text not null,
  skill_name text not null,
  level text not null,
  sort_order integer not null default 0,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.portfolio_projects enable row level security;
alter table public.portfolio_skills enable row level security;

drop policy if exists "Public can read published projects"
on public.portfolio_projects;

create policy "Public can read published projects"
on public.portfolio_projects
for select
to anon, authenticated
using (published = true);

drop policy if exists "Public can read published skills"
on public.portfolio_skills;

create policy "Public can read published skills"
on public.portfolio_skills
for select
to anon, authenticated
using (published = true);
